# Basic Information 
title: WEI-WEI WANG
cn_title: 「王偉偉」
position: Postgraduate Student
# department: School of Telecommunications Engineering
affiliation: Xidian University
affiliation_link: https://www.xidian.edu.cn/
affiliation_logo: ./assets/img/xidian.svg #./assets/img/university-logo-small-horizontal-white-156eae9527.svg
location: Xi'an, China
email: wweiwei@ieee.org

# Search Engine Optimization (SEO)
keywords: weiweiw weiwei  wangweiwei  weiweiwang
canonical: https://joe-weir-wong.github.io/
description: Wei-wei Wang is a Ph.D. students at School of Telecommunications Engineering, Xidian University. His research interests include Algebraic Coding and Cryptography.

# The option is used to enable the Johns Hopkins templates.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: true

# Links
link_type: icon #text/icon
# google_scholar: https://scholar.google.com/citations?user=NyUwUmIAAAAJ
# orcid: https://orcid.org/0000-0002-3619-8966
# researchgate: https://www.researchgate.net/profile/Kun-Yan-24
# clarivate: https://webofscience.clarivate.cn/wos/author/record/HLX-1711-2023
# scopus: https://www.scopus.com/authid/detail.uri?authorId=58088423400
twitter: https://x.com/weir_wong
github_link: https://github.com/Joe-weir-Wong
cv_link: ./assets/files/Weir_CV.pdf
linkedin: https://www.linkedin.com/in/wen-zhong-9a59771a5/

# Images 
avatar: ./assets/img/weir.jpg
favicon: ./assets/img/icon.png
favicon_dark: ./assets/img/icon.png

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true


# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
#clustrmaps_id: 

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
